[tool.poetry]
name = "gt_assessment"
version = "0.1.0"
description = "GovTech Senior Data Engineer assessment repository"
authors = ["pingmadhaninsg@gmail.com"]
packages = [{ include = "gt_assessment" }]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1"
sqlite-utils = "^3.41"
jupyter = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^8.0"
black = "^24.0"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
